server:
  port: 8080 # Porta para o auth-service, conforme o documento de arquitetura

spring:
  application:
    name: auth-service # Nome da aplicação
  data:
    mongodb:
      # SUA URI DE CONEXÃO DO MONGODB ATLAS INSERIDA AQUI
      uri: mongodb+srv://admin:admin@cluster0.prstvrf.mongodb.net/auth_db?retryWrites=true&w=majority&appName=Cluster0

jwt:
  secret: SuaChaveSecretaSuperSeguraENaoObviaParaAssinaturaDoJWT1234567890abcdef # Altere para uma string longa e aleatória
  expiration: 86400000 # Tempo de expiração em milissegundos (24 horas)